(* begin-package-description
The Test package manages:

* Unit test definitions
* Automatic running of tests

end-package-description *)

(* begin-module-use-description
Module Discuss handles:

* Nothing yet. Bug reporting eventually.

end-module-use-description *)
MODULE Test; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Test.
