(* begin-package-description
The Test package manages:

* Unit test definitions
* Automatic running of tests
* Performance instrumentation
* Performance testing reporting
* Fuzz definition
* Fuzz testing and reporting

end-package-description *)

(* begin-module-short-description
Unit test definition, execution, and reporting
end-module-short-description *)

(* begin-module-use-description
Module Test handles:

* Nothing yet. Bug reporting eventually.

end-module-use-description *)
MODULE Test; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Test.
